#ifndef URP_PAYLOAD_FRAME_H
#define URP_PAYLOAD_FRAME_H

#include <stdint.h>

/* Shared wire-layout values for the managed codec and native consumers. */
#define URP_FRAME_MAGIC "URPCK01\0"
#define URP_FRAME_TRAILER_MAGIC "URTRAIL1"
#define URP_FRAME_COMMON_HEADER_SIZE UINT16_C(112)
#define URP_FRAME_V1_HEADER_SIZE URP_FRAME_COMMON_HEADER_SIZE
#define URP_FRAME_V2_HEADER_SIZE UINT16_C(136)
#define URP_FRAME_TRAILER_SIZE UINT16_C(24)
#define URP_FRAME_SHA256_SIZE UINT16_C(32)

#define URP_FRAME_VERSION_V1 UINT16_C(1)
#define URP_FRAME_VERSION_V2 UINT16_C(2)
#define URP_FRAME_DEFLATE_FLAG UINT32_C(1)
#define URP_FRAME_MACHINE_AARCH64 UINT16_C(183)
#define URP_FRAME_TYPE_DYN UINT16_C(3)

#define URP_FRAME_VERSION_OFFSET UINT16_C(8)
#define URP_FRAME_HEADER_SIZE_OFFSET UINT16_C(10)
#define URP_FRAME_FLAGS_OFFSET UINT16_C(12)
#define URP_FRAME_MACHINE_OFFSET UINT16_C(16)
#define URP_FRAME_TYPE_OFFSET UINT16_C(18)
#define URP_FRAME_SOURCE_NAME_SIZE_OFFSET UINT16_C(20)
#define URP_FRAME_SOURCE_SIZE_OFFSET UINT16_C(24)
#define URP_FRAME_ENCODED_SIZE_OFFSET UINT16_C(32)
#define URP_FRAME_ENCODED_OFFSET_OFFSET UINT16_C(40)
#define URP_FRAME_SOURCE_SHA256_OFFSET UINT16_C(48)
#define URP_FRAME_ENCODED_SHA256_OFFSET UINT16_C(80)

#define URP_FRAME_TRAILER_FRAME_OFFSET UINT16_C(8)
#define URP_FRAME_TRAILER_LENGTH_OFFSET UINT16_C(16)

#define URP_FRAME_V2_HOST_ABI_OFFSET UINT16_C(112)
#define URP_FRAME_V2_RESERVED_BEFORE_CAPABILITIES_OFFSET UINT16_C(116)
#define URP_FRAME_V2_REQUIRED_CAPABILITIES_OFFSET UINT16_C(120)
#define URP_FRAME_V2_ENTRY_NAME_SIZE_OFFSET UINT16_C(128)
#define URP_FRAME_V2_RESERVED_AFTER_ENTRY_NAME_SIZE_OFFSET UINT16_C(132)

#define URP_FRAME_MAX_SOURCE_NAME UINT64_C(4096)
#define URP_FRAME_MAX_SOURCE_SIZE (UINT64_C(256) * UINT64_C(1024) * UINT64_C(1024))
#define URP_FRAME_MAX_ENCODED_SIZE (UINT64_C(256) * UINT64_C(1024) * UINT64_C(1024))
#define URP_FRAME_MAX_WRAPPER_SIZE (UINT64_C(512) * UINT64_C(1024) * UINT64_C(1024))

#endif
